### ISSUE TITLE
"squizlabs/php_codesniffer": "~1.4"

### ISSUE THREAD

**Issue by dereuromark** [h4cc/phpqatools#10]
Why does this use a totally outdated version?
This prevents all tools depending on this library to use the 2.x versions.

Please either remove or update this dependency.

**Comment by h4cc** [comment]
Thanks for that info.
Yep, some parts of the metapackage are quite outdated but still stable. Cant remember what lead to this constellation but there where some missing releases on packagist i think.

Might you check out this example for 2.0?
https://github.com/h4cc/phpqatools/tree/example-for-2-0

**Comment by h4cc** [comment]
I am unsure about the phpunit version requirement `~4|~5`.

@dereuromark What do you think?

**Comment by h4cc** [comment]
@dereuromark ping

**Comment by dereuromark** [comment]
I dont know about that :)
